### ISSUE TITLE
TODO Outline lessons and establish branching pattern for code versions from lesson 1 - 6

### ISSUE THREAD

**Issue by alexander-morris** [koii-network/ezsandbox#2]

**Comment by somali0128** [comment]
Add on:
Branch layout:
- main  //This branch should include the Lesson 1 folder and "Welcome"
- lesson 2  //This branch should include the Lesson 2 folder and the Previous Lesson folder(Lesson 1)
- lesson 3  //This branch should include the Lesson 3 folder and the Previous Lesson folder(Lesson 1 + Lesson 2)
...
Please follow this outline :)
@

**Comment by somali0128** [comment]
Done
