### ISSUE TITLE
Add part 1.4 - deploying a task

### ISSUE THREAD

**Issue by labrocadabro** [koii-network/ezsandbox#22]
In part 2, it just says "if you're not familiar with deploying a task..." If someone is starting from the absolute basics, then they *wouldn't* know how to deploy a task. So it makes sense to me that part of lesson one should be instructions on how to do so, rather than just giving a link to the documentation.

Alternatively, make deployment 1.3 and modifying the task 1.4.

**Comment by mabrar02** [comment]
We have existing documentation to deploy a task so I referred the user there. Do you think we should still explain or give more emphasis to the existing documentation?
