### ISSUE TITLE
Update task format in each lessons

### ISSUE THREAD

**Issue by somali0128** [koii-network/ezsandbox#27]
Each lessons task template need an update, specific in koiiNode.js

Please refer of this PR and update the tasks :) 

https://gitlab.com/koii-network/dev-blue/k2-task-template/-/commit/ecc7dfcc927fe7e1a5f1dbde1d4a42c9e587b380
https://gitlab.com/koii-network/dev-blue/k2-task-template/-/commit/844288191ec2837975fcc0207dcd81dcd4a836b6

**Comment by labrocadabro** [comment]
I checked each of the four existing tasks and the changes above are already implemented.
