### ISSUE TITLE
Fix namespace wrapper issue across multiple files

### ISSUE THREAD

**Issue by marsrobertson** [koii-network/ezsandbox#55]
In some places: `const { namespaceWrapper } = require('./_koiiNode/koiiNode');`

Depending on the folder structure may need to add `..` to indicate parent directory.

For example here: https://github.com/koii-network/ezsandbox/blob/281008e2f8423a79a8013c90f906ec0b450d24f0/Lesson%202/file-sharing/after/task/fileUtils/storeFile.js#L8

And here: https://github.com/koii-network/ezsandbox/blob/efafc2dc63fbd03e8b73e9a882315ea1464be396/Lesson%202/upnp-basics/after/routes.js#L7

_(the list above is non-exhaustive)_

**Comment by labrocadabro** [comment]
This will be fixed by #68 - we're now using an NPM package.
