### ISSUE TITLE
Lesson 4 - link to Gitlab from publicly available docs that requires a login

### ISSUE THREAD

**Issue by marsrobertson** [koii-network/ezsandbox#60]
> You can see an example from the Twitter Archive task [here](https://gitlab.com/koii-network/dev-blue/task-X/-/blob/main/namespaceWrapper.js?ref_type=heads#L579-592)

Here isthe code: https://github.com/koii-network/ezsandbox/blob/67906b2e6b5ca9a278c3784c8ea77fa5e1a4bab9/Lesson%204/README.md#L155

**Comment by labrocadabro** [comment]
I've removed the referenced section for now because it refers to namespaceWrapper, which is now a package and can't be easily edited.
