### ISSUE TITLE
Finnie is problematic

### ISSUE THREAD

**Issue by chaollapark** [koii-network/ezsandbox#89]
Hello I was trying to delpoy, but apparently there is a problem with finnie (Or I'm just too much of a noob).

![Screen Shot 2024-07-12 at 12 06 47 PM](https://github.com/user-attachments/assets/d8061a61-c4cd-422f-b8cb-5194768506b0)

I make a finnie wallet (which is actually suggested by the documentation) and I deleted my old wallet (or maybe just keys - which were empty since I transferred everything to the new one).

This has to be a bug, I put the wallet in the koii interface using the settings > account > get new key (I'm not a 100% sure of that though, but my finnie wallet is definitely connected to koii)

**Comment by labrocadabro** [comment]
You shouldn't need to use Finnie for deployment. Your issue here was most likely that you didn't run any tasks in your node with this staking key before you tried to deploy.
